# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'NewsApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NewsApp
pod 'Kingfisher', '~> 5.0'
pod 'Alamofire', '~> 5.0.0-beta.5'
end
